import { createPreset } from './create-preset'
import { startupLaunchpadSchema } from '@/lib/schemas/startup-launchpad'
import { portfolioSchema } from '@/lib/schemas/portfolio'
import { bistroSchema } from '@/lib/schemas/bistro'
import { blogSchema } from '@/lib/schemas/blog'
import { shopSchema } from '@/lib/schemas/shop'
import { comingSoonSchema } from '@/lib/schemas/coming-soon'
import { linkInBioSchema } from '@/lib/schemas/link-in-bio'
import { eventSchema } from '@/lib/schemas/event'
import { agencySchema } from '@/lib/schemas/agency'
import { resumeSchema } from '@/lib/schemas/resume'

export const startupPresets = [
  createPreset(
    startupLaunchpadSchema,
    'saas-blue',
    {
      'hero.headline': 'Build faster.\nShip smarter.',
      'hero.subheadline': 'Enterprise-grade infrastructure for modern SaaS teams. Deploy in minutes, scale to millions.',
      'hero.badge': '🚀 Early access — join 500+ teams',
      'hero.ctaLabel': 'Start free trial →',
      'hero.footnote': '14-day trial, no credit card',
      'hero.bgColor': '#0b1a2e',
      'hero.textColor': '#f0f9ff',
      'hero.accentColor': '#3b82f6',
      'features.sectionTitle': 'Everything you need to scale',
      'features.accentColor': '#3b82f6',
      'features.items': [
        { icon: '🚀', title: 'Blazing fast', desc: 'Edge-optimized delivery with sub-50ms response times worldwide.' },
        { icon: '🔐', title: 'Enterprise security', desc: 'SOC 2 certified with end-to-end encryption and audit logging.' },
        { icon: '📊', title: 'Real-time analytics', desc: 'Dashboards that update in real-time. No refreshes needed.' },
        { icon: '🔌', title: 'API-first', desc: 'REST & GraphQL APIs. Integrate with your existing stack in minutes.' },
      ],
      'pricing.sectionTitle': 'Simple pricing, no surprises',
      'pricing.accentColor': '#3b82f6',
      'pricing.plans': [
        { name: 'Hobby', price: '0', period: '/mese', cta: 'Inizia gratis', highlighted: 'false', features: 'Fino a 5 progetti|1 GB storage|Community support' },
        { name: 'Pro', price: '39', period: '/mese', cta: 'Prova 14 giorni', highlighted: 'true', features: 'Progetti illimitati|50 GB storage|Priority support|API access|Team up to 5' },
        { name: 'Enterprise', price: '149', period: '/mese', cta: 'Contattaci', highlighted: 'false', features: 'Tutto di Pro|SSO & SAML|99.99% SLA|Dedicated infra|Supporto 24/7' },
      ],
      'faq.sectionTitle': 'FAQ',
      'faq.items': [
        { question: 'Posso passare da un piano all\'altro?', answer: 'Sì, puoi fare upgrade o downgrade in qualsiasi momento. Il cambio è immediato.' },
        { question: 'Offrite sconti per startup?', answer: 'Assolutamente sì. Il nostro programma per startup offre il piano Pro gratuito per 6 mesi.' },
        { question: 'Come funziona il periodo di prova?', answer: '14 giorni gratuiti con accesso completo a tutte le feature del piano Pro, senza carta di credito.' },
      ],
      'cta.headline': 'Ready to scale up?',
      'cta.subtext': 'Join 10,000+ teams already building with us. Start your free trial today.',
      'cta.ctaLabel': 'Get started for free',
      'cta.bgColor': '#3b82f6',
      'cta.textColor': '#ffffff',
    },
    'SaaS Blue',
    'Landing page SaaS moderna con palette blu. Ideale per piattaforme B2B e strumenti digitali.',
  ),
  createPreset(
    startupLaunchpadSchema,
    'dark-app',
    {
      'hero.headline': 'The next generation\nof productivity.',
      'hero.subheadline': 'Minimal, powerful, and designed for deep focus. Your team\'s new command center.',
      'hero.badge': '✦ Disponibile ora',
      'hero.ctaLabel': 'Scarica gratis →',
      'hero.footnote': 'Mac · Windows · Linux',
      'hero.bgColor': '#0d0d0d',
      'hero.textColor': '#f5f5f5',
      'hero.accentColor': '#22d3ee',
      'features.sectionTitle': 'Strumenti essenziali, zero distrazioni',
      'features.accentColor': '#22d3ee',
      'features.items': [
        { icon: '⚡', title: 'Velocità estrema', desc: 'Apri e chiudi in un istante. Zero attese, zero lag.' },
        { icon: '🎯', title: 'Focus mode', desc: 'Attiva la modalità scrittura e scompare tutto il superfluo.' },
        { icon: '🔗', title: 'Collegamenti rapidi', desc: 'Collega note, task e progetti con un semplice @mention.' },
        { icon: '☁️', title: 'Sync istantaneo', desc: 'Tutto sincronizzato in tempo reale su tutti i tuoi dispositivi.' },
      ],
      'pricing.sectionTitle': 'Scegli il tuo piano',
      'pricing.accentColor': '#22d3ee',
      'pricing.plans': [
        { name: 'Base', price: '0', period: '/mese', cta: 'Inizia gratis', highlighted: 'false', features: 'Note illimitate|3 integrazioni|Sync 2 dispositivi' },
        { name: 'Pro', price: '12', period: '/mese', cta: 'Prova 30 giorni', highlighted: 'true', features: 'Tutto di Base|Integrazioni illimitate|Sync illimitato|AI assistant|Temi personalizzati' },
        { name: 'Team', price: '28', period: '/utente/mese', cta: 'Contattaci', highlighted: 'false', features: 'Tutto di Pro|Workspace condivisi|Admin dashboard|Audit log|Supporto priority' },
      ],
      'faq.sectionTitle': 'Domande',
      'faq.items': [
        { question: 'I miei dati sono sicuri?', answer: 'Crittografia end-to-end su tutti i piani. I dati sono ospitati su server europei certificati GDPR.' },
        { question: 'Posso usare l\'app offline?', answer: 'Sì, l\'app funziona completamente offline. Le modifiche si sincronizzano quando torni online.' },
        { question: 'È disponibile in italiano?', answer: 'Sì, l\'interfaccia è tradotta in italiano, inglese, francese, tedesco e spagnolo.' },
      ],
      'cta.headline': 'Entra nel futuro del lavoro',
      'cta.subtext': 'Unisciti a 50.000 professionisti che usano già la nostra piattaforma. Scarica ora, gratis.',
      'cta.ctaLabel': 'Scarica gratuitamente',
      'cta.bgColor': '#0d0d0d',
      'cta.textColor': '#22d3ee',
    },
    'Dark App',
    'Landing page per app desktop in stile dark-mode. Perfetta per software di produttività e creativi.',
  ),
  createPreset(
    startupLaunchpadSchema,
    'fintech',
    {
      'hero.headline': 'Il tuo bank\nintelligente.',
      'hero.subheadline': 'Gestisci finanze, investimenti e risparmi in un unico posto. Banking per il 21° secolo.',
      'hero.badge': '✦ Banca autorizzata · Banca d\'Italia',
      'hero.ctaLabel': 'Apri il conto →',
      'hero.footnote': 'Nessun canone · Apertura in 5 minuti',
      'hero.bgColor': '#f0fdf4',
      'hero.textColor': '#052e16',
      'hero.accentColor': '#16a34a',
      'features.sectionTitle': 'Più di un conto corrente',
      'features.accentColor': '#16a34a',
      'features.items': [
        { icon: '📱', title: '100% digitale', desc: 'Apri il conto dal tuo smartphone in 5 minuti. Niente carta, niente filiali.' },
        { icon: '📈', title: 'Investimenti automatici', desc: 'Il tuo denaro lavora per te con portafogli bilanciati automaticamente.' },
        { icon: '🔒', title: 'Sicurezza bancaria', desc: 'Autenticazione biometrica, notifiche in tempo reale, assicurazione contro le frodi.' },
        { icon: '💳', title: 'Carta inclusa', desc: 'Carta di debito fisica e virtuale senza canone. Prelievi gratis in tutta Europa.' },
      ],
      'pricing.sectionTitle': 'Piani trasparenti',
      'pricing.accentColor': '#16a34a',
      'pricing.plans': [
        { name: 'Base', price: '0', period: '/mese', cta: 'Apri conto', highlighted: 'false', features: 'Conto corrente|Carta di debito|Bonifici SEPA gratis|Prelievi ATM EU' },
        { name: 'Plus', price: '4.99', period: '/mese', cta: 'Passa a Plus', highlighted: 'true', features: 'Tutto di Base|Investimento automatico|Budgeting avanzato|Cashback 1%|Assicurazione acquisti' },
        { name: 'Premium', price: '9.99', period: '/mese', cta: 'Scopri Premium', highlighted: 'false', features: 'Tutto di Plus|Assistente IA personale|Trading azionario|Carta metal|Supporto priority 24/7' },
      ],
      'faq.sectionTitle': 'Domande frequenti',
      'faq.items': [
        { question: 'Quanto tempo ci vuole per aprire il conto?', answer: 'In media 5 minuti. Ti basta un documento d\'identità valido e il tuo smartphone.' },
        { question: 'Ci sono commissioni sui bonifici?', answer: 'Tutti i bonifici SEPA in entrata e uscita sono gratuiti su tutti i piani.' },
        { question: 'I miei depositi sono garantiti?', answer: 'Sì, siamo una banca autorizzata con Fondo Interbancario di Tutela dei Depositi fino a 100.000€.' },
      ],
      'cta.headline': 'Passa a una banca che ti capisce',
      'cta.subtext': 'Oltre 200.000 clienti hanno già scelto di cambiare. Apri il tuo conto in 5 minuti.',
      'cta.ctaLabel': 'Apri il conto — è gratis',
      'cta.bgColor': '#16a34a',
      'cta.textColor': '#ffffff',
    },
    'Fintech',
    'Landing page per startup fintech. Design professionale con palette verde. Ideale per neobank e servizi finanziari.',
  ),
]

export const portfolioPresets = [
  createPreset(
    portfolioSchema,
    'artisan',
    {
      'hero.headline': 'Giulia Martini\nCeramista & Artigiana',
      'hero.subheadline': 'Forme contemporanee, ispirazione antica. Ogni pezzo è unico.',
      'hero.ctaLabel': 'Vedi le collezioni',
      'hero.bgColor': '#faf5eb',
      'hero.textColor': '#2d1f12',
      'hero.accentColor': '#b5714a',
      'work.sectionTitle': 'Collezioni',
      'work.layout': 'uniform',
      'work.items': [
        { image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800&q=80', caption: 'Linea Terra — 2026' },
        { image: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=800&q=80', caption: 'Collezione Mare — 2025' },
        { image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80', caption: 'Vasi scultura — mostra Milano' },
        { image: 'https://images.unsplash.com/photo-1490312278390-ab64016e0aa9?w=800&q=80', caption: 'Set da tavola — edizione limitata' },
        { image: 'https://images.unsplash.com/photo-1612435823141-da85ef5f5148?w=800&q=80', caption: 'Laboratorio — processo creativo' },
        { image: 'https://images.unsplash.com/photo-1595756947614-6046ba6c3446?w=800&q=80', caption: 'Installazione — Design Week' },
      ],
      'about.eyebrow': 'Chi sono',
      'about.headline': 'Lavoro l\'argilla\nda vent\'anni, e non ho smesso di stupirmi.',
      'about.body': 'Sono una ceramista con base a Faenza, dove ho aperto il mio laboratorio nel 2016. Le mie forme prendono ispirazione dal paesaggio romagnolo: le linee dolci delle colline, i colori della terra, la luce del mare vicino. Ogni pezzo è tornito a mano, smaltato con tecniche tradizionali e cotto in forno a legna. Collaboro con gallerie d\'arte, interior designer e ristoranti che cercano ceramiche d\'autore per i loro spazi.',
      'about.image': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
      'about.bgColor': '#ffffff',
      'about.textColor': '#2d1f12',
      'contact.sectionTitle': 'Richiedi un preventivo',
      'contact.subtext': 'Hai un progetto o vuoi visitare il laboratorio? Scrivimi e ti risponderò entro 24 ore.',
      'contact.submitLabel': 'Invia richiesta',
      'contact.bgColor': '#faf5eb',
      'contact.textColor': '#2d1f12',
    },
    'Artisan Portfolio',
    'Portfolio artigiano con palette calda e terrosa. Per ceramisti, falegnami e maker.',
  ),
  createPreset(
    portfolioSchema,
    'bold-portfolio',
    {
      'hero.headline': 'Elena Russo\nArt Director',
      'hero.subheadline': 'Visual storytelling per brand che vogliono lasciare il segno.',
      'hero.ctaLabel': 'Vedi i progetti',
      'hero.bgColor': '#0a0a0a',
      'hero.textColor': '#ffffff',
      'hero.accentColor': '#ff3d3d',
      'work.sectionTitle': 'Progetti selezionati',
      'work.layout': 'two-col',
      'work.items': [
        { image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80', caption: 'Campagna FW25 — Heliotrope' },
        { image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80', caption: 'Editoriale — Vogue Italia' },
        { image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800&q=80', caption: 'Visual identity — Blvck Paris' },
        { image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80', caption: 'Direzione artistica — Festival 2025' },
        { image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&q=80', caption: 'Campagna beauty — Aesop' },
        { image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80', caption: 'Book personale — 2026' },
      ],
      'about.eyebrow': 'Bio',
      'about.headline': 'Direzione artistica\ncon un occhio di riguardo per il dettaglio.',
      'about.body': 'Sono un\'Art Director con 12 anni di esperienza tra Milano, Parigi e New York. Ho lavorato con brand di moda, cosmetica e lusso, dirigendo campagne editoriali e digitali. Il mio approccio unisce rigore concettuale e libertà visiva: ogni progetto parte da un\'idea forte e si sviluppa attraverso immagini, tipografia e movimento con la stessa attenzione al dettaglio.',
      'about.image': 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400&q=80',
      'about.bgColor': '#141414',
      'about.textColor': '#ffffff',
      'contact.sectionTitle': 'Contattami',
      'contact.subtext': 'Cerchi un art director per il tuo prossimo progetto? Parliamone.',
      'contact.bgColor': '#0a0a0a',
      'contact.textColor': '#ffffff',
    },
    'Bold Portfolio',
    'Portfolio audace in dark mode con accenti rossi. Per art director, stylist e creativi.',
  ),
]

export const bistroPresets = [
  createPreset(
    bistroSchema,
    'pizzeria',
    {
      'hero.headline': 'Da Ezio\nPizza napoletana dal 1968.',
      'hero.subheadline': 'Aperti martedì–domenica · 19:30–23:30 · Via Roma 42, Napoli',
      'hero.ctaLabel': 'Prenota un tavolo',
      'hero.bgColor': '#1c0f08',
      'hero.textColor': '#faf0e6',
      'hero.accentColor': '#cd5c28',
      'story.eyebrow': 'La nostra storia',
      'story.headline': 'Tre generazioni\ndi pizzaioli napoletani.',
      'story.body': 'Da Ezio nasce nel 1968, quando nonno Ezio aprì il primo forno a legna in via Roma. Oggi siamo alla terza generazione e la nostra passione per la pizza napoletana è rimasta intatta. Usiamo solo ingredienti DOP: pomodori San Marzano, mozzarella di bufala campana, olio extravergine del Cilento. Il nostro impasto matura 48 ore ed è cotto in forno a legna a 485°C per esattamente 60 secondi. Siamo stati premiati come miglior pizzeria tradizionale d\'Italia nel 2024.',
      'story.image': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80',
      'story.bgColor': '#faf0e6',
      'story.textColor': '#1c0f08',
      'menu.sectionTitle': 'Il nostro menu',
      'menu.subtext': 'Impasto 48 ore, ingredienti DOP, forno a legna. Tutto è fatto a mano, ogni giorno.',
      'menu.groups': [
        { groupName: 'Classiche', items: 'Margherita — 8€\nMarinara — 7€\nDiavola — 10€\nCapricciosa — 11€\nQuattro formaggi — 12€' },
        { groupName: 'Specialità', items: 'Ezio (bufala, pomodorini, basilico) — 14€\nTartufo (crema al tartufo, funghi) — 16€\nParma (prosciutto crudo, rucola) — 15€\nPistacchio (crema al pistacchio, mortadella) — 15€' },
        { groupName: 'Dolci', items: 'Tiramisù della casa — 6€\nPastiera napoletana — 7€\nSfogliatella calda — 5€\nGelato artigianale — 4€' },
      ],
      'reviews.sectionTitle': 'Cosa dicono di noi',
      'reviews.items': [
        { quote: 'La vera pizza napoletana. Leggera, digeribile, con ingredienti di altissima qualità. Il miglior rapporto qualità-prezzo di Napoli.', author: 'Paolo C.', role: 'Napoli', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
        { quote: 'Veniamo da Roma apposta per mangiare qui. L\'impasto 48 ore si sente: è un\'altra cosa rispetto alla pizza media.', author: 'Sara M.', role: 'Roma', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
        { quote: 'La Diavola è la mia preferita. Il loro olio piccante fatto in casa è pazzesco. Prenotate sempre, è sempre pieno.', author: 'Marco V.', role: 'Milano', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
      ],
      'book.sectionTitle': 'Prenota il tuo tavolo',
      'book.subtext': 'Aperti martedì–domenica dalle 19:30. Per gruppi oltre 8 persone, chiamaci allo 081 123 4567.\nLa domenica a pranzo siamo aperti dalle 12:30.',
      'book.bgColor': '#1c0f08',
      'book.textColor': '#faf0e6',
    },
    'Pizzeria',
    'Sito per pizzeria napoletana con menu autentico e storia famigliare.',
  ),
  createPreset(
    bistroSchema,
    'wine-bar',
    {
      'hero.headline': 'Enobar\nVini naturali, piccoli produttori.',
      'hero.subheadline': 'Aperti mercoledì–domenica · 18:00–01:00 · Via Torino 28, Milano',
      'hero.ctaLabel': 'Prenota una degustazione',
      'hero.bgColor': '#1a1410',
      'hero.textColor': '#f0e8d5',
      'hero.accentColor': '#8b2f3a',
      'story.eyebrow': 'Il progetto',
      'story.headline': 'Vini che raccontano\nuna storia, non una marca.',
      'story.body': 'Enobar nasce dalla passione di due sommelier per i vini naturali, quelli che parlano del territorio e della stagione. Selezioniamo personalmente piccoli produttori italiani e francesi che lavorano con metodi tradizionali, nessun additivo, nessuna fretta. Ogni mese cambiamo la carta dei vini per offrire solo le migliori annate del momento. Abbiamo 120 etichette, di cui 30 al calice, e una selezione di formaggi e salumi artigianali che cambia ogni settimana.',
      'story.image': 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800&q=80',
      'story.bgColor': '#f0e8d5',
      'story.textColor': '#1a1410',
      'menu.sectionTitle': 'Carta dei vini — Marzo',
      'menu.subtext': 'Selezione mensile. Ogni bottiglia racconta un luogo, un produttore, una stagione. Chiedici consiglio, ti guideremo.',
      'menu.groups': [
        { groupName: 'Bolle', items: 'Franciacorta Contadi Castaldi — 12€\nProsecco Valdobbiadene Col Vetoraz — 9€\nPét-Nat Vino di Anna — 11€\nChampagne Bérêche & Fils — 22€' },
        { groupName: 'Bianchi', items: 'Friulano Venica & Venica — 8€\nVerdicchio dei Castelli di Jesi Bucci — 10€\nChablis Domaine Pattes Loup — 16€\nGavi di Gavi La Toledana — 9€' },
        { groupName: 'Rossi', items: 'Barbera d\'Alpi Vajra — 10€\nRosso di Montalcino Argiano — 14€\nCôtes-du-Rhône Domaine Gramenon — 11€\nEtna Rosso Graci — 13€' },
      ],
      'reviews.sectionTitle': 'I clienti dicono',
      'reviews.items': [
        { quote: 'Finalmente un posto dove il vino naturale è preso sul serio. La selezione è curatissima e il personale sa davvero consigliare.', author: 'Alessandro F.', role: 'Milano', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
        { quote: 'Atmosfera incredibile, vini mai sentiti prima e stuzzicheria fantastica. Il posto perfetto per una serata tra amici.', author: 'Giulia N.', role: 'Milano', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
        { quote: 'I taglieri di formaggi sono spettacolari e abbinati perfettamente ai vini. Un\'esperienza enogastronomica di alto livello.', author: 'Riccardo T.', role: 'Bergamo', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
      ],
      'book.sectionTitle': 'Prenota una degustazione',
      'book.subtext': 'Offriamo degustazioni guidate per gruppi fino a 12 persone. Chiamaci al 02 123 4567 o compila il form.\nDegustazione base 35€/persona (5 vini + formaggi).',
      'book.bgColor': '#1a1410',
      'book.textColor': '#f0e8d5',
    },
    'Wine Bar',
    'Sito per wine bar con focus su vini naturali. Palette calda, elegante.',
  ),
]

export const blogPresets = [
  createPreset(
    blogSchema,
    'tech-blog',
    {
      'hero.headline': 'Bytes & Bits\nTecnologia, codice, pensieri laterali.',
      'hero.subheadline': 'Articoli su ingegneria del software, architettura e vita da sviluppatore.',
      'hero.ctaLabel': 'Leggi gli ultimi post',
      'hero.bgColor': '#0f172a',
      'hero.textColor': '#f1f5f9',
      'hero.accentColor': '#38bdf8',
      'feed.sectionTitle': 'Ultimi articoli',
      'feed.items': [
        { title: 'Perché abbiamo riscritto tutto in Rust (e cosa abbiamo imparato)', excerpt: 'Dopo 4 anni di Python, abbiamo riscritto il nostro core in Rust. Performance, safety e una lezione di umiltà. I benchmark e le nostre impressioni a caldo.', date: '20 marzo 2026', image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80', tag: 'engineering' },
        { title: 'Il lato oscuro delle microservizi (e quando evitarli)', excerpt: 'Le microservizi non sono la risposta a tutto. Tre casi studio dove un monoliteceo ben progettato avrebbe fatto meglio.', date: '8 marzo 2026', image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800&q=80', tag: 'architecture' },
        { title: 'Come funziona effettivamente il garbage collector di Go', excerpt: 'Un viaggio nel GC di Go: mark-sweep, STW, pacer, e come scrivere codice che lo aiuta a fare meno lavoro.', date: '22 febbraio 2026', image: 'https://images.unsplash.com/photo-1515879218367-8466d910auj8?w=800&q=80', tag: 'go' },
        { title: 'Guida definitiva alla gestione degli errori in TypeScript', excerpt: 'Dai try-catch ai Result type, passando per Either e pattern matching. Cosa usare e quando, con esempi concreti da production code.', date: '10 febbraio 2026', image: 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=800&q=80', tag: 'typescript' },
      ],
      'about.eyebrow': 'Chi scrive',
      'about.headline': 'Sono Marco Viti.\nScrivo codice e articoli da 15 anni.',
      'about.body': 'Sono un software engineer e tech lead con base a Bologna. Lavoro come backend engineer per una scale-up europea. Scrivo di programmazione, architettura software e ingegneria della produttività. Credo che la tecnologia vada spiegata in modo chiaro, senza jargon inutile. Ogni tanto parlo anche di libri, musica e caffè specialità. Tutti i post sono scritti a mano, senza AI.',
      'about.image': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
      'about.bgColor': '#0f172a',
      'about.textColor': '#f1f5f9',
    },
    'Tech Blog',
    'Blog tecnico con palette dark. Per sviluppatori, ingegneri e appassionati di tecnologia.',
  ),
  createPreset(
    blogSchema,
    'travel-blog',
    {
      'hero.headline': 'Zaino in spalla\nViaggi lenti, storie vere.',
      'hero.subheadline': 'Racconti di viaggio, fotografia, cibo e incontri. Un nuovo post ogni due giovedì.',
      'hero.ctaLabel': 'Leggi il diario di bordo',
      'hero.bgColor': '#f0f7f4',
      'hero.textColor': '#1a2e24',
      'hero.accentColor': '#2d8f6f',
      'feed.sectionTitle': 'Diario di bordo',
      'feed.items': [
        { title: 'Sul treno notturno da Milano a Palermo', excerpt: '12 ore attraverso l\'Italia. Scompartimenti vintage, chiacchiere con sconosciuti e l\'alba sullo Stretto. Il viaggio più bello che si possa fare in Italia.', date: '15 marzo 2026', image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80', tag: 'italia' },
        { title: 'Lisbona: guida ai quartieri che amano i locali', excerpt: 'Dimentica l\'Alfafa turistica. Ti porto a Graça, Campo de Ourique e alla scoperta delle migliori pasteis de nata fuori dal circuito.', date: '28 febbraio 2026', image: 'https://images.unsplash.com/photo-1503252947848-7338d3c92b5f?w=800&q=80', tag: 'portogallo' },
        { title: 'Come viaggiare (davvero) leggeri', excerpt: 'Zaino da 28 litri per un mese. Cosa porto, cosa lascio, e perché possedere meno cose migliora ogni viaggio.', date: '10 febbraio 2026', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', tag: 'consigli' },
        { title: 'Sakura season: un giorno a Kyoto', excerpt: 'Ciliegi in fiore, templi silenziosi, tè matcha e un\'emozione che le foto non possono catturare. Cronaca di una giornata perfetta.', date: '25 gennaio 2026', image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80', tag: 'giappone' },
      ],
      'about.eyebrow': 'Chi c\'è dietro',
      'about.headline': 'Fotografo, scrittore,\nviaggiatore lento.',
      'about.body': 'Sono Chiara Bellini, una viaggiatrice slow con base a Bologna. Lavoro come fotografa freelance e scrivo di viaggi per magazine cartacei e digitali. Il mio stile di viaggio è lento, fuori dai circuiti turistici, attento alle persone e ai dettagli. Zaino in spalla è nato come diario personale nel 2020 e oggi è un punto di riferimento per chi cerca un turismo più autentico e consapevole.',
      'about.image': 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400&q=80',
      'about.bgColor': '#ffffff',
      'about.textColor': '#1a2e24',
    },
    'Travel Blog',
    'Blog di viaggi con palette verde salvia. Per storyteller e amanti dei viaggi lenti.',
  ),
]

export const shopPresets = [
  createPreset(
    shopSchema,
    'beauty-shop',
    {
      'hero.headline': 'Naturale è meglio.\nCosmesi botanica artigianale.',
      'hero.subheadline': 'Saponi, creme e oli essenziali. Tutto fatto a mano con ingredienti biologici di provenienza locale.',
      'hero.ctaLabel': 'Scopri i prodotti',
      'hero.bgColor': '#f8f0eb',
      'hero.textColor': '#2d1f12',
      'hero.accentColor': '#c48a6b',
      'catalog.sectionTitle': 'I più amati',
      'catalog.items': [
        { image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&q=80', name: 'Sapone al carbone',       price: '12€',  tag: 'bestseller' },
        { image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&q=80', name: 'Crema viso alla calendula',price: '28€',  tag: 'nuovo' },
        { image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&q=80', name: 'Olio corpo alla lavanda',  price: '22€',  tag: '' },
        { image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&q=80', name: 'Balsamo labbra al cacao',   price: '8€',   tag: 'bestseller' },
        { image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&q=80', name: 'Deodorante naturale',       price: '14€',  tag: 'nuovo' },
        { image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&q=80', name: 'Maschera capelli all\'olio', price: '18€',  tag: '' },
      ],
      'reviews.sectionTitle': 'Le vostre recensioni',
      'reviews.items': [
        { quote: 'La crema viso alla calendula è incredibile. La uso da due mesi e la mia pelle non è mai stata così luminosa. E l\'odore... divino.', author: 'Francesca L.', role: 'Verona', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
        { quote: 'Compro i saponi da oltre un anno e non torno più ai prodotti industriali. La qualità si sente, la differenza sulla pelle è reale.', author: 'Simone R.', role: 'Firenze', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
        { quote: 'Regalo sempre i vostri prodotti. Il packaging è bellissimo e i profumi naturali sono unici. Il balsamo labbra al cacao non lo lascio mai a casa.', author: 'Giorgia T.', role: 'Bologna', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
      ],
      'faq.sectionTitle': 'Domande sui prodotti',
      'faq.items': [
        { question: 'I prodotti sono testati su animali?', answer: 'No, mai. Tutti i nostri prodotti sono cruelty-free e certificati Cosmos Organic. Non testiamo su animali dal primo giorno.' },
        { question: 'Quanto durano i prodotti?', answer: 'I saponi durano circa 4 settimane. Le creme e gli oli hanno una scadenza di 12 mesi dall\'apertura perché senza conservanti chimici.' },
        { question: 'Fate spedizioni internazionali?', answer: 'Sì, spediamo in tutta Europa. La consegna in Italia è 2-3 giorni lavorativi, in Europa 5-8 giorni.' },
      ],
      'newsletter.headline': 'Ricevi novità e promozioni',
      'newsletter.subtext': 'Una volta al mese, solo cose belle: nuovi prodotti, sconti per iscritti e storie dal laboratorio.',
      'newsletter.ctaLabel': 'Iscriviti alla newsletter',
      'newsletter.bgColor': '#f8f0eb',
      'newsletter.textColor': '#2d1f12',
    },
    'Beauty Shop',
    'E-commerce per cosmesi naturale artigianale. Palette calda e accogliente.',
  ),
  createPreset(
    shopSchema,
    'coffee-shop',
    {
      'hero.headline': 'Il caffè specialità\ndalla tostatura artigianale.',
      'hero.subheadline': 'Mono-origine, lotto singolo, tostatura di 48 ore prima della spedizione. Il caffè come dovrebbe essere.',
      'hero.ctaLabel': 'Acquista online',
      'hero.bgColor': '#1c1814',
      'hero.textColor': '#ede0d4',
      'hero.accentColor': '#c77d4b',
      'catalog.sectionTitle': 'Disponibili ora',
      'catalog.items': [
        { image: 'https://images.unsplash.com/photo-1559009233-1a14a80f0453?w=600&q=80', name: 'Ethiopia Yirgacheffe',       price: '16€',  tag: 'bestseller' },
        { image: 'https://images.unsplash.com/photo-1559009233-1a14a80f0453?w=600&q=80', name: 'Colombia La Palma',           price: '15€',  tag: 'nuovo' },
        { image: 'https://images.unsplash.com/photo-1559009233-1a14a80f0453?w=600&q=80', name: 'Kenya Nyeri AB',              price: '18€',  tag: '' },
        { image: 'https://images.unsplash.com/photo-1559009233-1a14a80f0453?w=600&q=80', name: 'Indonesia Sumatra Mandheling',price: '17€',  tag: '' },
        { image: 'https://images.unsplash.com/photo-1559009233-1a14a80f0453?w=600&q=80', name: 'Guatemala Antigua',            price: '15€',  tag: 'bestseller' },
        { image: 'https://images.unsplash.com/photo-1559009233-1a14a80f0453?w=600&q=80', name: 'Costa Rica Tarrazú',           price: '16€',  tag: 'nuovo' },
        { image: 'https://images.unsplash.com/photo-1559009233-1a14a80f0453?w=600&q=80', name: 'Brasil Yellow Bourbon',        price: '14€',  tag: '' },
        { image: 'https://images.unsplash.com/photo-1559009233-1a14a80f0453?w=600&q=80', name: 'Etiopia Natural Process',      price: '19€',  tag: 'edizione limitata' },
      ],
      'reviews.sectionTitle': 'I clienti dicono',
      'reviews.items': [
        { quote: 'Il miglior caffè che abbia mai provato. L\'Ethiopia Yirgacheffe è un\'esplosione di fragranze che non sapevo esistessero in una tazza di caffè.', author: 'Davide F.', role: 'Roma', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
        { quote: 'La freschezza è imbattibile. Tostano e spediscono lo stesso giorno, il caffè arriva che è ancora vivo. Cambia tutto rispetto al supermercato.', author: 'Elena B.', role: 'Milano', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
        { quote: 'Abbonamento mensile regalato a mio marito. Oggi non potrebbe farne a meno. La qualità è costante e la selezione variata ogni mese.', author: 'Anna R.', role: 'Torino', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
      ],
      'faq.sectionTitle': 'FAQ',
      'faq.items': [
        { question: 'Quanto costa la spedizione?', answer: 'La spedizione è gratuita per ordini sopra i 30€. Per ordini inferiori, 4,90€ in Italia e 9,90€ in Europa.' },
        { question: 'Come conservare il caffè?', answer: 'Conserva il caffè in un contenitore ermetico, lontano da luce, calore e umidità. Non metterlo in frigo! Usalo entro 30 giorni dalla tostatura.' },
        { question: 'Fate abbonamenti?', answer: 'Sì, abbiamo un abbonamento mensile flessibile con spedizione gratuita, prezzo bloccato e possibilità di cambiare la selezione ogni mese. Puoi sospendere quando vuoi.' },
      ],
      'newsletter.headline': 'Caffè, niente spam',
      'newsletter.subtext': 'Nuove origini, guide alla preparazione e consigli dalla torrefazione. Una mail a settimana, massimo.',
      'newsletter.ctaLabel': 'Iscrivimi',
      'newsletter.bgColor': '#1c1814',
      'newsletter.textColor': '#ede0d4',
    },
    'Coffee Shop',
    'E-commerce per caffè specialità. Design scuro ed elegante, atmosfera da torrefazione.',
  ),
]

export const comingSoonPresets = [
  createPreset(
    comingSoonSchema,
    'product-hunt',
    {
      'hero.headline': 'Something big\nis brewing.',
      'hero.subheadline': 'We\'re building the easiest way to deploy AI models. Get early access and exclusive launch perks.',
      'hero.ctaLabel': 'Get early access',
      'hero.bgColor': '#0a0a1a',
      'hero.textColor': '#f0f0ff',
      'hero.accentColor': '#6c5ce7',
      'metrics.items': [
        { value: '3.847', label: 'waiting for launch' },
        { value: 'Q3 2026', label: 'expected launch' },
        { value: '25+', label: 'countries reached' },
      ],
      'metrics.bgColor': '#12122a',
      'metrics.textColor': '#f0f0ff',
      'waitlist.sectionTitle': 'Join the waitlist',
      'waitlist.subtext': 'Be among the first to try it. Early adopters get 6 months free, private community access, and a lifetime discount.',
      'waitlist.submitLabel': 'Join waitlist',
      'waitlist.emailPlaceholder': 'Your email address',
      'waitlist.showName': 'false',
      'waitlist.bgColor': '#0a0a1a',
      'waitlist.textColor': '#f0f0ff',
    },
    'Product Hunt Coming Soon',
    'Pagina pre-lancio in inglese per startup tech. Stile Product Hunt. Ottima per raccogliere iscrizioni internazionali.',
  ),
  createPreset(
    comingSoonSchema,
    'wedding',
    {
      'hero.headline': 'Ci sposiamo!\nAlessia & Francesco',
      'hero.subheadline': '12 settembre 2026 · Borgo San Vito, Toscana',
      'hero.ctaLabel': 'Conferma la tua presenza',
      'hero.bgColor': '#fcf7f0',
      'hero.textColor': '#3d2b1f',
      'hero.accentColor': '#c4907a',
      'metrics.items': [
        { value: '♡', label: 'vi aspettiamo' },
        { value: '12.09.26', label: 'il grande giorno' },
        { value: '80+', label: 'invitati' },
      ],
      'metrics.bgColor': '#faf0e6',
      'metrics.textColor': '#3d2b1f',
      'waitlist.sectionTitle': 'Conferma la tua presenza',
      'waitlist.subtext': 'Fateci sapere se potrete essere con noi entro il 31 luglio 2026. Borgo San Vito dispone di camere per chi vorrà fermarsi dopo il ricevimento.',
      'waitlist.submitLabel': 'Conferma presenza',
      'waitlist.emailPlaceholder': 'La tua email',
      'waitlist.showName': 'true',
      'waitlist.bgColor': '#fcf7f0',
      'waitlist.textColor': '#3d2b1f',
    },
    'Wedding',
    'Pagina pre-matrimonio con conto alla rovescia e conferma presenza. Palette chiara e romantica.',
  ),
]

export const linkInBioPresets = [
  createPreset(
    linkInBioSchema,
    'minimal',
    {
      'links.name': 'Lorenzo Bianchi',
      'links.bio': 'Product designer · Milano',
      'links.avatar': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
      'links.bgColor': '#f5f5f5',
      'links.textColor': '#171717',
      'links.accentColor': '#171717',
      'links.links': [
        { label: 'Portfolio',    url: 'https://lorenzobianchi.design', emoji: '→' },
        { label: 'LinkedIn',     url: 'https://linkedin.com/in/lorenzo-bianchi', emoji: '→' },
        { label: 'Dribbble',     url: 'https://dribbble.com/lorenzob', emoji: '→' },
        { label: 'Email',        url: 'mailto:lorenzo@example.com', emoji: '→' },
      ],
    },
    'Minimal Bio',
    'Link in bio minimalista in bianco e nero. Per designer e professionisti.',
  ),
  createPreset(
    linkInBioSchema,
    'creator',
    {
      'links.name': 'Sofia Re',
      'links.bio': 'Content creator · Fashion & lifestyle · 📍 Roma',
      'links.avatar': 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
      'links.bgColor': '#fff0f3',
      'links.textColor': '#1f0a12',
      'links.accentColor': '#d43f6b',
      'links.links': [
        { label: 'Instagram',     url: 'https://instagram.com/sofiare', emoji: '📸' },
        { label: 'YouTube',       url: 'https://youtube.com/@sofiare', emoji: '🎥' },
        { label: 'TikTok',        url: 'https://tiktok.com/@sofiare', emoji: '🎵' },
        { label: 'Newsletter',    url: 'https://sofiare.substack.com', emoji: '✉️' },
        { label: 'Shop my look',  url: 'https://shop.sofiare.com', emoji: '🛍️' },
        { label: 'Contatti',      url: 'mailto:hello@sofiare.com', emoji: '📩' },
      ],
    },
    'Creator Bio',
    'Link in bio per content creator. Palette rosa, link social. Ideale per fashion e lifestyle.',
  ),
]

export const eventPresets = [
  createPreset(
    eventSchema,
    'music-festival',
    {
      'hero.headline': 'Altura Festival\nDue giorni di musica indie.',
      'hero.subheadline': '5–6 luglio 2026 · Parco della Musica, Perugia · 15 band',
      'hero.ctaLabel': 'Compra i biglietti',
      'hero.bgColor': '#0d0d1a',
      'hero.textColor': '#ffffff',
      'hero.accentColor': '#f59e0b',
      'program.sectionTitle': 'Line-up',
      'program.date': '5–6 luglio 2026',
      'program.items': [
        { time: '15:00', title: 'Apertura cancelli',                       speaker: '',               location: 'Ingresso' },
        { time: '16:30', title: 'Luna Moth · live',                        speaker: 'folk elettronica', location: 'Palco A' },
        { time: '18:00', title: 'I Cani di Strada · live',                 speaker: 'indie rock',       location: 'Palco A' },
        { time: '19:30', title: 'DJ Set — Margherita Vicario',             speaker: 'pop',              location: 'Palco B' },
        { time: '21:00', title: 'Califano · live',                         speaker: 'indie pop',        location: 'Palco A' },
        { time: '22:30', title: 'After party con DJ Mariposa',             speaker: '',                 location: 'Palco B' },
      ],
      'venue.eyebrow': 'Il luogo',
      'venue.headline': 'Parco della Musica,\nnel verde di Perugia.',
      'venue.body': 'Il Parco della Musica è un anfiteatro naturale immerso nel verde, a 10 minuti dal centro di Perugia. Raggiungibile con navetta gratuita dalla stazione FS. L\'area campeggio è inclusa nel biglietto: porta la tua tenda o prenota una delle nostre glamping experience. Ci saranno food truck, mercato artigianale e un\'area relax con vista sulla vallata umbra.',
      'venue.image': 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80',
      'venue.bgColor': '#f5f0e8',
      'venue.textColor': '#0d0d1a',
      'registration.sectionTitle': 'Biglietti',
      'registration.subtext': 'Abbigliamento disponibile fino a esaurimento posti. Il weekend include accesso a tutti i concerti, area campeggio e navetta dal centro.',
      'registration.submitLabel': 'Acquista biglietto',
      'registration.showMessage': 'false',
      'registration.bgColor': '#0d0d1a',
      'registration.textColor': '#ffffff',
    },
    'Music Festival',
    'Pagina festival musicale con line-up. Palette dark e oro. Perfetta per eventi musicali e culturali.',
  ),
  createPreset(
    eventSchema,
    'tech-conference',
    {
      'hero.headline': 'DevCon Verona 2026\nIl futuro del backend.',
      'hero.subheadline': '18–19 giugno · Teatro Ristori · 600 sviluppatori',
      'hero.ctaLabel': 'Registrati ora',
      'hero.bgColor': '#0b1120',
      'hero.textColor': '#f0f6ff',
      'hero.accentColor': '#3b82f6',
      'program.sectionTitle': 'Programma — Day 1',
      'program.date': '18 giugno 2026',
      'program.items': [
        { time: '09:00', title: 'Keynote: Lo stato del backend nel 2026',       speaker: 'Alice Neri',   location: 'Sala Principale' },
        { time: '10:15', title: 'Rust per microservizi: esperienze sul campo',   speaker: 'Marco Wolf',   location: 'Sala B' },
        { time: '11:30', title: 'Event-driven architecture con Kafka',           speaker: 'Sofia Riva',   location: 'Sala A' },
        { time: '13:00', title: 'Pranzo + lightning talks',                      speaker: '',             location: 'Foyer' },
        { time: '14:30', title: 'Database moderni: oltre il modello relazionale',speaker: 'Luca Bianchi',  location: 'Sala Principale' },
        { time: '16:00', title: 'Panel: Scaling senza impazzire',                speaker: '4 speaker',    location: 'Sala Principale' },
      ],
      'venue.eyebrow': 'La sede',
      'venue.headline': 'Teatro Ristori,\nnel centro di Verona.',
      'venue.body': 'Il Teatro Ristori è uno dei teatri storici più belli d\'Italia, situato a pochi passi dall\'Arena di Verona. Le sale ristrutturate offrono spazio per 600 partecipanti con tre track parallele. Verona è facilmente raggiungibile in treno (Alta Velocità da Milano in 1h, da Venezia in 1h10) e aereo (aeroporto VRN a 15 minuti). Abbiamo convenzioni con 4 hotel nel centro storico.',
      'venue.image': 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
      'venue.bgColor': '#f8fafc',
      'venue.textColor': '#0b1120',
      'registration.sectionTitle': 'Iscriviti',
      'registration.subtext': 'Early bird disponibile fino al 30 aprile. Incluso: accesso a tutti i track, pranzi, coffee break e materiale della conferenza.',
      'registration.submitLabel': 'Registrati',
      'registration.showMessage': 'false',
      'registration.bgColor': '#0b1120',
      'registration.textColor': '#f0f6ff',
    },
    'Tech Conference',
    'Pagina conferenza sviluppatori con programma e relatori. Palette dark blu professionale.',
  ),
]

export const agencyPresets = [
  createPreset(
    agencySchema,
    'luxury',
    {
      'hero.headline': 'NERO Studio\nIdentity, spazio, materia.',
      'hero.subheadline': 'Consulenza creativa per brand del lusso e della moda.',
      'hero.ctaLabel': 'Scopri i progetti',
      'hero.bgColor': '#0d0d0d',
      'hero.textColor': '#ffffff',
      'hero.accentColor': '#d4af37',
      'work.sectionTitle': 'Progetti selezionati',
      'work.layout': 'two-col',
      'work.items': [
        { image: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=800&q=80', caption: 'Visual identity — Maison Noir' },
        { image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80', caption: 'Packaging — Profumo Oud 1924' },
        { image: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?w=800&q=80', caption: 'Residenza privata — Lake Como' },
        { image: 'https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80', caption: 'Interior curation — Showroom Milano' },
        { image: 'https://images.unsplash.com/photo-1501084291732-13b1ba8f0ebc?w=800&q=80', caption: 'Campagna editoriale — FW26' },
        { image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80', caption: 'Design system — Gioielleria Vivi' },
      ],
      'services.sectionTitle': 'Aree di competenza',
      'services.accentColor': '#d4af37',
      'services.items': [
        { icon: '◇', title: 'Brand identity', desc: 'Sistemi visivi completi per brand di lusso. Ogni dettaglio è pensato per comunicare eccellenza.' },
        { icon: '◇', title: 'Spazio & materia', desc: 'Direzione artistica di spazi fisici, vetrine, showroom. L\'architettura come espressione del brand.' },
        { icon: '◇', title: 'Editoriale & digital', desc: 'Campagne, cataloghi, piattaforme digitali. La stessa cura artigianale, su ogni supporto.' },
      ],
      'clients.sectionTitle': 'Clienti',
      'clients.items': [
        { quote: 'Un raro equilibrio tra visione artistica e rigore professionale. Hanno compreso la nostra estetica meglio di chiunque altro.', author: 'Isabella V.', role: 'Direttrice Creativa, Maison Noir', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
        { quote: 'Il nuovo packaging ha ridisegnato la nostra percezione del prodotto. I clienti lo trattano come un oggetto da collezione.', author: 'Federico A.', role: 'CEO, Profumo Oud 1924', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
        { quote: 'Collaborare con NERO Studio significa entrare in un mondo dove ogni dettaglio è curato con ossessione. Il risultato parla da sé.', author: 'Camilla R.', role: 'Brand Manager, Gioielleria Vivi', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
      ],
      'work-with-us.headline': 'Un progetto di cui essere orgogliosi?',
      'work-with-us.subtext': 'Lavoriamo con un numero limitato di client all\'anno. Se hai un\'idea ambiziosa, siamo qui per ascoltarla.',
      'work-with-us.ctaLabel': 'Raccontaci il tuo progetto',
      'work-with-us.bgColor': '#0d0d0d',
      'work-with-us.textColor': '#ffffff',
    },
    'Luxury Agency',
    'Sito agenzia lusso con palette nero e oro. Per studi creativi che lavorano con brand di alta gamma.',
  ),
  createPreset(
    agencySchema,
    'minimal-agency',
    {
      'hero.headline': 'Copernico\nDesign che conta.',
      'hero.subheadline': 'Piccolo studio di design con base a Torino. Brand, digital, editoria.',
      'hero.ctaLabel': 'Vedi i lavori',
      'hero.bgColor': '#ffffff',
      'hero.textColor': '#0f0f0f',
      'hero.accentColor': '#2b2b2b',
      'work.sectionTitle': 'Lavori selezionati',
      'work.layout': 'uniform',
      'work.items': [
        { image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&q=80', caption: 'Brand identity — Fiorile' },
        { image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80', caption: 'Sito web — Libreria Tre Volte' },
        { image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=800&q=80', caption: 'Book design — Saggi Contemporanei' },
        { image: 'https://images.unsplash.com/photo-1496024840928-4c417adf211d?w=800&q=80', caption: 'Packaging — Olearia Picchio' },
        { image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80', caption: 'Campagna — Teatro Stabile Torino' },
        { image: 'https://images.unsplash.com/photo-1493612276216-ee3925520721?w=800&q=80', caption: 'Identity — Festival Gradiente' },
      ],
      'services.sectionTitle': 'Servizi',
      'services.accentColor': '#2b2b2b',
      'services.items': [
        { icon: '●', title: 'Brand identity', desc: 'Logo, tipografia, colori, applicazioni. Un sistema visivo coerente e riconoscibile nel tempo.' },
        { icon: '●', title: 'Web design', desc: 'Siti essenziali, veloci, accessibili. Design che mette i contenuti al centro.' },
        { icon: '●', title: 'Editoria', desc: 'Progettazione di libri, cataloghi, magazine. Formato cartaceo e digitale.' },
      ],
      'clients.sectionTitle': 'Collaborazioni',
      'clients.items': [
        { quote: 'Copernico ha capito subito chi siamo e cosa volevamo comunicare. Il sito è esattamente come lo immaginavamo, ma meglio.', author: 'Elena F.', role: 'Libreria Tre Volte', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
        { quote: 'Professionalità e sensibilità estetica rare. Il packaging che hanno progettato per noi ha vinto un premio, ma soprattutto ha fatto innamorare i clienti.', author: 'Marco P.', role: 'Olearia Picchio', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
        { quote: 'Lavorare con loro è stato semplice. Il che, nel nostro settore, è il più grande complimento che si possa fare.', author: 'Chiara M.', role: 'Teatro Stabile Torino', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80' },
      ],
      'work-with-us.headline': 'Hai un progetto?',
      'work-with-us.subtext': 'Siamo un piccolo studio e lavoriamo con pochi client alla volta. Se vuoi fare bella roba, parliamone.',
      'work-with-us.ctaLabel': 'Scrivici',
      'work-with-us.bgColor': '#ffffff',
      'work-with-us.textColor': '#0f0f0f',
    },
    'Minimal Agency',
    'Sito agenzia minimalista bianco e nero. Per studi di design, grafici e creativi.',
  ),
]

export const resumePresets = [
  createPreset(
    resumeSchema,
    'dev',
    {
      'hero.headline': 'Davide Costa\nFull-Stack Developer',
      'hero.subheadline': 'React, Node, Go — cerco opportunità in remoto · Disponibile da giugno 2026',
      'hero.ctaLabel': 'Scarica CV',
      'hero.bgColor': '#0f172a',
      'hero.textColor': '#f1f5f9',
      'hero.accentColor': '#38bdf8',
      'summary.eyebrow': 'Profilo',
      'summary.headline': '7 anni a costruire\ncose che funzionano.',
      'summary.body': 'Sono uno sviluppatore full-stack con 7 anni di esperienza. Ho lavorato in startup, scale-up e come freelance. Il mio stack principale è React/TypeScript per il frontend, Node.js e Go per il backend, PostgreSQL e Redis per i dati. Ho una passione per le performance, l\'architettura pulita e i test che servono davvero. Parlo inglese (C1) e spagnolo (B2). Cerco ruoli full-time in remoto per aziende europee o americane.',
      'summary.image': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
      'summary.bgColor': '#ffffff',
      'summary.textColor': '#0f172a',
      'highlights.items': [
        { value: '7 anni', label: 'esperienza' },
        { value: '15+', label: 'progetti completati' },
        { value: 'C1', label: 'inglese' },
        { value: 'Open', label: 'a remoto' },
      ],
      'highlights.bgColor': '#1e293b',
      'highlights.textColor': '#f1f5f9',
      'links.name': 'Davide Costa',
      'links.bio': 'Full-Stack Developer',
      'links.avatar': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
      'links.bgColor': '#0f172a',
      'links.textColor': '#f1f5f9',
      'links.accentColor': '#38bdf8',
      'links.links': [
        { label: 'GitHub',     url: 'https://github.com/davidecosta', emoji: '💻' },
        { label: 'LinkedIn',   url: 'https://linkedin.com/in/davidecosta', emoji: '🔗' },
        { label: 'Portfolio',  url: 'https://davidecosta.dev', emoji: '→' },
        { label: 'Email',      url: 'mailto:davide@example.com', emoji: '✉️' },
      ],
    },
    'CV Developer',
    'CV digitale per sviluppatori full-stack. Palette dark blu, tono tecnico e moderno.',
  ),
  createPreset(
    resumeSchema,
    'executive',
    {
      'hero.headline': 'Roberta Fontana\nChief Marketing Officer',
      'hero.subheadline': 'Growth & brand per scale-up · Consulenza · Board advisory',
      'hero.ctaLabel': 'Scarica profilo completo',
      'hero.bgColor': '#faf8f5',
      'hero.textColor': '#1a1410',
      'hero.accentColor': '#8b3a3a',
      'summary.eyebrow': 'Executive summary',
      'summary.headline': '15 anni di marketing\nper brand e scale-up.',
      'summary.body': 'Executive con 15 anni di esperienza in marketing digitale, brand strategy e crescita. Ho guidato team di 40+ persone in aziende come Glovo, Satispay e diversi VC-backed startup. Competenze in: brand positioning, performance marketing, CRM, content strategy e comunicazione corporate. Ho lanciato campagne in 12 paesi europei con budget complessivi di oltre 20M€. Parlo italiano, inglese e francese. Cerco ruoli CMO fractional o full-time per scale-up in fase Series A/B.',
      'summary.image': 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400&q=80',
      'summary.bgColor': '#ffffff',
      'summary.textColor': '#1a1410',
      'highlights.items': [
        { value: '15 anni', label: 'esperienza' },
        { value: '40+', label: 'team lead' },
        { value: '20M€', label: 'budget gestiti' },
        { value: '12', label: 'paesi coperti' },
      ],
      'highlights.bgColor': '#8b3a3a',
      'highlights.textColor': '#faf8f5',
      'links.name': 'Roberta Fontana',
      'links.bio': 'CMO & Growth Advisor',
      'links.avatar': 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400&q=80',
      'links.bgColor': '#1a1410',
      'links.textColor': '#faf8f5',
      'links.accentColor': '#d47a7a',
      'links.links': [
        { label: 'LinkedIn',     url: 'https://linkedin.com/in/roberta-fontana', emoji: '🔗' },
        { label: 'Portfolio',    url: 'https://roberta-fontana.com', emoji: '→' },
        { label: 'Email',        url: 'mailto:roberta@example.com', emoji: '✉️' },
      ],
    },
    'CV Executive',
    'CV digitale per profili executive e C-level. Palette chiara con accenti borgogna.',
  ),
]
